baseURL = "http://www.cin.ufpe.br/~jhcp/"
languageCode = "en-us"
title = "João Pimentel"
theme = "purehugo"

[params]
  description = "Professional web site for João Pimentel - Professor at UFRPE, based in Pernambuco, Brazil. Computer Science researcher, with focus on Software Engineering."

  twitterName = "joaohenriquep"
  dblpLink = "http://dblp.uni-trier.de/pers/hd/p/Pimentel_0001:Jo=atilde=o"
  googleScholarLink = "https://scholar.google.com.br/citations?user=2Ze85gcAAAAJ&hl=pt-BR&oi=ao"
  lattesLink = "http://lattes.cnpq.br/8257035194560179"

  rss = false
  hideShareOptions = true

  google_analytics = "UA-xxxxxx-xx"
